name = "EarthSurface"
uuid = "38f1a330-05d6-4413-9ecd-795277bd1ae7"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = 1.6
